/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

Drupal.behaviors.mylib = {
  attach: function attach() {
    var test = true;
    console.log('Hello Internet Explorer :)');
  }
};